### ISSUE TITLE
`PKGBUILD`: Downlaod rust dependencies into `$srcdir`, and download within `prepare()`.

### ISSUE THREAD

**Issue by dreirund** [aur-packaging/chatgpt-desktop-git#3]
Can you set `CARGO_HOME="${srcdir}/cargo` or similar _within_ `prepare()`, `build()` and `package()` to make rust download it's stuff into "${srcdir}" and not cluttering the home directory?

And can you move the download step of rust into `prepare()`, please? (There are download-only options for rust.)

Thanks for maintaining,  
regards!

**Comment by slithery0** [comment]
https://github.com/aur-packaging/chatgpt-desktop-git/pull/4

Can you please verify this PKGBUILD and let me know if I did it right or if I am missing anything you mentioned.
Thanks,
Regards.
